# SPDX-License-Identifier: Apache-2.0
# ZMK main on zephyr-tc32 (Zephyr 4.4), for every build (EXTRA_CONF_FILE):
# ZMK still includes <syscalls/...>, which Zephyr 4.4 only keeps behind a
# deprecated option.
CONFIG_LEGACY_GENERATED_INCLUDE_PATH=y
CONFIG_WARN_DEPRECATED=n
