#!/usr/bin/env python3
"""Write ota_vectors.h for the OTA host test: images made by telink_ota.py and the
HID frames it would send for them.

Usage: gen_ota_vectors.py <path to telink_ota.py> <output header>

SPDX-License-Identifier: GPL-3.0-or-later
"""
import importlib.util
import os
import random
import sys

spec = importlib.util.spec_from_file_location("telink_ota", sys.argv[1])
t = importlib.util.module_from_spec(spec)
spec.loader.exec_module(t)
rng = random.Random(8278)


def raw(n):
    b = bytearray(rng.randbytes(n))
    b[0:4] = bytes.fromhex("0e800000")
    b[8:12] = b"KNLT"
    b[0x18:0x1C] = bytes(4)
    return bytes(b)


def c_bytes(name, data):
    rows = [", ".join(f"0x{x:02x}" for x in data[i:i + 16]) for i in range(0, len(data), 16)]
    return f"static const uint8_t {name}[] = {{\n\t" + ",\n\t".join(rows) + "\n};\n"


def c_frames(name, frames):
    rows = ["{" + ", ".join(f"0x{x:02x}" for x in f) + "}" for f in frames]
    return f"static const uint8_t {name}[][{t.REPORT_LEN}] = {{\n\t" + ",\n\t".join(rows) + "\n};\n"


# 5,000 bytes: two flash sectors in the target slot; 8,200: three.
good = t.make_image(raw(5000))
good2 = t.make_image(raw(8200))
bad = bytearray(t.make_image(raw(4100)))
bad[-1] ^= 0x01  # wrong CRC-32
out = ["/* Generated by gen_ota_vectors.py; do not edit. */", "#include <stdint.h>", ""]
for name, img, check, start in (("good", good, True, t.CMD_START), ("good2", good2, True, t.CMD_START),
                                ("bad_crc", bytes(bad), False, t.CMD_START)):
    frames, last = t.frames(img, check=check, start=start)
    out += [c_bytes(f"ota_img_{name}", img), c_frames(f"ota_frames_{name}", frames),
            f"#define OTA_LAST_{name.upper()} {last}U", ""]
os.makedirs(os.path.dirname(sys.argv[2]), exist_ok=True)
open(sys.argv[2], "w").write("\n".join(out))
